export interface SondageDroitFormData {
  droitsDebut: string;
  loiSociete: string;
  protectionEgale: string;
  importanceConnaissance: string;
  protectionTorture: string;
  congeMaladie: string;
  licenciementSansMotif: string;
  responsabiliteEmployeur: string;
  conservationDonnees: string;
  bailleurExpulsion: string;
  refusContrat: string;
  augmentationLoyer: string;
  saisiBiens: string;
  ageResponsabilite: string;
  droitsContreEtat: string;
  differendContact: string;
  justiceGratuite: string;
  delaiAction: string;
  aideJuridictionnelle: string;
  cyberharcelement: string;
  resolutionAmiable: string;
  methodesResolution: string[];
  langageComplique: string;
  contactJuriste: string;
  simplifierDroits: string;
  prioriteApprentissage: string;
  matiereObligatoire: string;
}
